### ISSUE TITLE
Genesis state

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/beacon-challenge#16]
Thanks to Go's initial values, it should be very few lines of code. The non-default fields are `slot` (because GENESIS_SLOT != 0), `genesis_time`, `latest_eth1_data` plus a bit of boilerplate to process deposits and activations.

It doesn't fit nicely in the `func StateTransition(preState *BeaconState, block *BeaconBlock) (res *BeaconState, err error)` paradigm so I wouldn't include it in the line count. May be nice for completeness though.

**Comment by protolambda** [comment]
fixed in new repo
