### ISSUE TITLE
SSZ discussion

### ISSUE THREAD

**Issue by JustinDrake** [protolambda/beacon-challenge#4]
> enforcing ordered structs

Structs are definitely ordered. I don't think that's negotiable because fields must be ordered for Merkleisation to be well-defined.

> makes signing very unflexible

That's just signing for the phase 0 spec. People can define whatever signing logic suits them. Maybe that part of the spec should be put in the phase 0 doc instead.

> Introduce ssz-meta

Would introducing ssz-meta change the result of `hash_tree_root` in any way for phase 0? If so then it's just a presentational issue and easily fixable.

**Comment by protolambda** [comment]
discussed during EthCC, fixed, closing now. Works in new go-beacon-transition repo
